A = int(input('Digite o primeiro número: '))
B = int(input('Digite o segundo número: '))
C = int(input('Digite o terceiro número: '))
S = ((A**2) + (B**2) + (C**2))
print('A soma dos valores quadrados: {} , {} e {}. é: {}'.format(A, B, C, S))